#!/usr/bin/env bash
# Prints domain and subdomain info
print_domain_info() {
    dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | sed -E "s/$1./$2/g" | awk '{print "The subdomain "$1" is a "$4" record and points to "$5""}'
}

if [ "$#" -eq 2 ]; then
    print_domain_info "$2.$1" "$2"
else
    print_domain_info "www.$1" "www"
    print_domain_info "lb-01.$1" "lb-01"
    print_domain_info "web-01.$1" "web-01"
    print_domain_info "web-02.$1" "web-02"
fi
