#!/usr/bin/env bash
# Install nginx on your web server: web-01/web-92

apt-get -y update
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sed -i "24i\	add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
