#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

sed -i '$ a\frontend http' /etc/haproxy/haproxy.cfg
sed -i '$ a\        bind *:80\n        mode http\n        default_backend myservers' /etc/haproxy/haproxy.cfg
sed -i '$ a\backend myservers' /etc/haproxy/haproxy.cfg
sed -i '$ a\        balance roundrobin' /etc/haproxy/haproxy.cfg
sed -i '$ a\        server 97830-web-01 54.236.47.245:80 check' /etc/haproxy/haproxy.cfg
sed -i '$ a\        server 97830-web-02 100.26.156.253:80 check' /etc/haproxy/haproxy.cfg

service haproxy restart
