#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*

# update package info
apt-get -y update

config_update="\
frontend http
        bind *:80
        mode http
        default_backend myservers

backend myservers
        balance roundrobin
        server 97830-web-01 54.236.47.245:80 check
        server 97830-web-02 100.26.156.253:80 check
"

echo "$config_update" >> /etc/haproxy/haproxy.cfg
service haproxy restart
