#!/bin/bash

touch 1-who_am_i
touch 2-groups
touch 3-new_owner
touch 4-empty
touch 5-execute
touch 6-multiple_permissions
touch 7-everybody
touch 8-James_Bond
touch 9-John_Doe
touch 10-mirror_permissions
touch 11-directories_permissions
touch 12-directory_permissions
touch 13-change_group
