#!/usr/bin/env bash
# Nginx port 80 - Update symbolic link sites-available/default to sites-enabled
cd /etc/nginx/sites-enabled/ || exit
rm default
ln -s /etc/nginx/sites-available/default default
service nginx restart
