#!/usr/bin/env bash
# Nginx port 80 - Update symbolic link sites-available/default to sites-enabled
rm /etc/nginx/sites-enabled/default | exit
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx stop
