#!/usr/bin/env bash
# A bash script that displays Best School 10 times
i=0
while (("(i=$i+1) < 11"))
do
  if ((i == 4)); then
    echo "bad luck"
  elif ((i == 8)); then
    echo "good luck"
  else
    echo "Best School"
  fi
done
