#!/usr/bin/env bash
# A bash script that displays Best School 10 times
i=0
while (("(i=$i+1) < 21"))
do
  echo $i
  case "$i" in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
done
