#!/usr/bin/env bash
# Run Nginx as Nginx
cp -p /etc/nginx/nginx.conf{,.orig}
sed -i 's/user www-data/user user/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
